# Generated by Django 5.0.6 on 2025-01-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=255)),
                ("campaign_genre", models.CharField(max_length=255)),
                ("sub_genre", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_audience", models.TextField()),
                ("region", models.CharField(max_length=255)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
