# Generated by Django 5.0.6 on 2025-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_campaigninquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigninquiry",
            name="brand_contact",
            field=models.CharField(default="+919876543210", max_length=15),
        ),
        migrations.AddField(
            model_name="campaigninquiry",
            name="brand_email",
            field=models.EmailField(default="example@abc.com", max_length=254),
        ),
    ]
