# Generated by Django 5.0.6 on 2025-01-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_campaigninquiry_brand_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigninquiry",
            name="brand_contact",
            field=models.CharField(default="+91", max_length=15),
        ),
        migrations.AlterField(
            model_name="campaigninquiry",
            name="brand_email",
            field=models.EmailField(default=" ", max_length=254),
        ),
    ]
