# Generated by Django 5.1.7 on 2025-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaigninquiry_brand_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigninquiry',
            old_name='target_audience',
            new_name='describe_your_campaign',
        ),
        migrations.RemoveField(
            model_name='campaigninquiry',
            name='budget',
        ),
        migrations.AddField(
            model_name='campaigninquiry',
            name='Timeline',
            field=models.CharField(choices=[('1 time', '1 time'), ('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('12 months', '12 months'), ('13 months', '13 months'), ('14 months', '14 months'), ('15 months', '15 months'), ('16 months', '16 months'), ('17 months', '17 months'), ('18 months', '18 months'), ('19 months', '19 months'), ('20 months', '20 months'), ('21 months', '21 months'), ('22 months', '22 months'), ('23 months', '23 months'), ('24 months', '24 months'), ('25 months', '25 months'), ('26 months', '26 months'), ('27 months', '27 months'), ('28 months', '28 months'), ('29 months', '29 months'), ('30 months', '30 months'), ('31 months', '31 months'), ('32 months', '32 months'), ('33 months', '33 months'), ('34 months', '34 months'), ('35 months', '35 months'), ('36 months', '36 months'), ('37 months', '37 months'), ('38 months', '38 months'), ('39 months', '39 months'), ('40 months', '40 months'), ('41 months', '41 months'), ('42 months', '42 months'), ('43 months', '43 months'), ('44 months', '44 months'), ('45 months', '45 months'), ('46 months', '46 months'), ('47 months', '47 months'), ('48 months', '48 months')], default='1 time', max_length=20),
        ),
        migrations.AddField(
            model_name='campaigninquiry',
            name='budget_range',
            field=models.CharField(choices=[('Can’t disclose', 'Can’t disclose'), ('0-3 Lakhs', '0-3 Lakhs'), ('3-5 Lakhs', '3-5 Lakhs'), ('5-10 Lakhs', '5-10 Lakhs'), ('10-20 Lakhs', '10-20 Lakhs'), ('20-50 Lakhs', '20-50 Lakhs'), ('50 Lakhs+', '50 Lakhs+')], default='Can’t disclose', max_length=50),
        ),
        migrations.AddField(
            model_name='campaigninquiry',
            name='creator_type',
            field=models.CharField(choices=[('Nano', 'Nano'), ('Micro', 'Micro'), ('Macro', 'Macro'), ('Mega', 'Mega'), ('Mega A+', 'Mega A+'), ('Celebrities', 'Celebrities'), ('Premium Celebrities', 'Premium Celebrities')], default='Nano', max_length=50),
        ),
        migrations.AddField(
            model_name='campaigninquiry',
            name='select_influencer_platform',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more platforms'),
        ),
    ]
