# Generated by Django 5.1.7 on 2025-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_rename_target_audience_campaigninquiry_describe_your_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigninquiry',
            name='campaign_genre',
        ),
        migrations.RemoveField(
            model_name='campaigninquiry',
            name='sub_genre',
        ),
        migrations.AddField(
            model_name='campaigninquiry',
            name='creator_genre',
            field=models.JSONField(blank=True, default=list, help_text='Select any three or more creator genres'),
        ),
        migrations.AddField(
            model_name='campaigninquiry',
            name='service',
            field=models.CharField(choices=[('Influencer Marketing', 'Influencer Marketing'), ('Celebrity Marketing', 'Celebrity Marketing'), ('Visit Store/Place', 'Visit Store/Place'), ('Barter Campaign', 'Brarter Campaign'), ('UGC', 'UGC'), ('Celebrity Endorsement', 'Celebrity Endorsement'), ('Digital Marketing', 'Digital Marketing'), ('Other', 'Other')], default='Influencer Marketing', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaigninquiry',
            name='select_influencer_platform',
            field=models.JSONField(blank=True, choices=[('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Lifestyle', 'Lifestyle'), ('Food', 'Food'), ('Travel', 'Travel'), ('Fitness', 'Fitness'), ('Gaming', 'Gaming'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Finance', 'Finance'), ('Health', 'Health'), ('Real Estate', 'Real Estate')], help_text='Select one or more platforms'),
        ),
    ]
