# Generated by Django 5.1.7 on 2025-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_remove_campaigninquiry_campaign_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninquiry',
            name='select_influencer_platform',
            field=models.JSONField(blank=True, default=list, help_text='Select one or more platforms'),
        ),
    ]
