# Generated by Django 5.0 on 2026-02-22 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Graph API"),
                            ("instagram", "Instagram Graph API"),
                            ("google", "Google API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("followers", models.PositiveIntegerField(default=0)),
                ("profile_views", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("engagement", models.PositiveIntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("gender_split", models.JSONField(blank=True, default=dict)),
                ("city_split", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at",),
            },
        ),
        migrations.CreateModel(
            name="InfluencerPlatformConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Graph API"),
                            ("instagram", "Instagram Graph API"),
                            ("google", "Google API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_account_id", models.CharField(max_length=255)),
                (
                    "access_token",
                    models.TextField(
                        help_text="OAuth access token issued by the selected platform."
                    ),
                ),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("influencer", "platform", "external_account_id")},
            },
        ),
    ]
