# Generated by Django 5.0 on 2026-02-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencermetricsnapshot",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="authentication.influencerplatformconnection",
            ),
        ),
        migrations.AddField(
            model_name="influencermetricsnapshot",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="influencerplatformconnection",
            name="creator_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nano", "Nano Creator (1K-10K)"),
                    ("micro", "Micro Creator (10K-100K)"),
                    ("mid", "Mid-tier Creator (100K-500K)"),
                    ("macro", "Macro Creator (500K-1M)"),
                    ("mega", "Mega Creator (1M+)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="influencerplatformconnection",
            name="latest_followers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencerplatformconnection",
            name="profile_handle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="influencermetricsnapshot",
            name="source",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook Page"),
                    ("instagram", "Instagram Account"),
                    ("youtube", "YouTube Channel"),
                    ("google_analytics", "Google Analytics Property"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="influencerplatformconnection",
            name="access_token",
            field=models.TextField(help_text="OAuth access token for this account"),
        ),
        migrations.AlterField(
            model_name="influencerplatformconnection",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook Page"),
                    ("instagram", "Instagram Account"),
                    ("youtube", "YouTube Channel"),
                    ("google_analytics", "Google Analytics Property"),
                ],
                max_length=30,
            ),
        ),
    ]
